### ISSUE TITLE
Can not run(Illegal byte scequence)

### ISSUE THREAD

**Issue by JeffYuY** [KoljaB/Linguflex#16]
Whever I try to run, it says something wrong with GBK

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\Lingu\Linguflex\lingu\__init__.py", line 5, in <module>
    from lingu.core.settings import cfg  # noqa: F401
  File "D:\Lingu\Linguflex\lingu\core\settings.py", line 104, in <module>
    cfg = SettingsManager(settings_file).get
  File "D:\Lingu\Linguflex\lingu\core\settings.py", line 30, in __init__
    self.settings: Dict[str, Any] = self.load_settings()
  File "D:\Lingu\Linguflex\lingu\core\settings.py", line 61, in load_settings
    return yaml.safe_load(file)
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 4404: illegal multibyte sequence
```

**Comment by KoljaB** [comment]
Something wrong with the settings.yaml, error message suggests around character 4404 in that file.
Is that the original one from the repo or did you change it?

**Comment by JeffYuY** [comment]
It's the original one, I used the command mentioned in the doc

**Comment by JeffYuY** [comment]
Yea I cloned with the git url mentioned in the doc

**Comment by JeffYuY** [comment]
I think I found the problem.
my settings.yaml's sentence_delimiters looks like this
`sentence_delimiters: .?!。`
where I located character 4404 is 。, and since I opened it in vscode, it warned me this character might be confused to other characters. I think in this case, the reader program doesn't recognize this symbol.
I know this symbol, it's the chinese version of a period, and I have encountered this problem on my own before.
Could I just delete this symbol and move on, or change it to another one?

**Comment by JeffYuY** [comment]
I deleted the symbol and it tried booting up, but I got another error
`FileNotFoundError: Could not find module 'D:\Lingu\Linguflex\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.`
That file indeed doesn't exist.
Here's the full log:
```
📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

 0:01.9|Logging initialized.
 0:01.9|  [brain] using local language model "llama3.1:8b" with ollama provider
 0:02.9|  [brain] warm up llm
 0:02.9|  performing warmup with error handling
 0:02.9|  [brain] warming up the Ollama model...
 0:02.9|  [brain] model llama3.1:8b not found. Attempting to pull the model...
pulling manifest
pulling 667b0c1932bc... 100% ▕████████████████████████████████████████████████████████▏ 4.9 GB
pulling 948af2743fc7... 100% ▕████████████████████████████████████████████████████████▏ 1.5 KB
pulling 0ba8f0e314b4... 100% ▕████████████████████████████████████████████████████████▏  12 KB
pulling 56bb8bd477a5... 100% ▕████████████████████████████████████████████████████████▏   96 B
pulling 455f34728c9b... 100% ▕████████████████████████████████████████████████████████▏  487 B
verifying sha256 digest
writing manifest
success
 1:08.1|  [brain] successfully pulled model: llama3.1:8b
 1:08.1|  [brain] warming up the Ollama model...
 1:29.9|  [brain] ollama model is ready and responsive
 1:29.9|  [brain] brain initialized
START
 1:31.6|  [core] starting module manager
 1:31.6|  [core] creating modules
 1:31.6|importing modules from: D:\Lingu\Linguflex\lingu\modules
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\brain
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\interpreter
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\listen
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\mimic
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\music
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\os_apps
 1:31.6|+ importing D:\Lingu\Linguflex\lingu\modules\speech
 1:31.6|  [core] loading start modules
 1:31.6|  + importing file lingu.modules.brain.state
 1:31.6|    + state found: BrainState
 1:31.6|  + importing file lingu.modules.interpreter.state
 1:31.6|    + state found: InterpreterState
 1:31.6|  + importing file lingu.modules.listen.state
 1:31.6|    + state found: ListenState
 1:31.6|  + importing file lingu.modules.mimic.state
 1:31.6|    + state found: MimicState
 1:31.6|  + importing file lingu.modules.music.state
 1:31.6|    + state found: MusicState
 1:31.6|  + importing file lingu.modules.os_apps.state
 1:31.7|    + state found: OS_Apps_State
 1:31.7|  + importing file lingu.modules.speech.state
 1:31.7|    + state found: SpeechState
 1:31.7|  + importing file lingu.modules.brain.logic
 1:31.7|    + logic found: BrainLogic
 1:31.7|  + importing file lingu.modules.interpreter.logic
 1:40.7|    + logic found: InterpreterLogic
 1:40.7|  + importing file lingu.modules.listen.logic
 1:54.0|    + logic found: ListenLogic
 1:54.0|  + importing file lingu.modules.mimic.logic
 1:54.0|    + logic found: MimicLogic
 1:54.0|  + importing file lingu.modules.music.logic
Traceback (most recent call last):
  File "D:\Lingu\Linguflex\lingu\ui\notify.py", line 298, in check_and_proceed
    callback()    # Call the callback function
  File "D:\Lingu\Linguflex\lingu\core\run.py", line 33, in on_notification_visible
    lingu.start()
  File "D:\Lingu\Linguflex\lingu\core\lingu.py", line 60, in start
    self.modules.load_start_modules()
  File "D:\Lingu\Linguflex\lingu\core\modules.py", line 199, in load_start_modules
    self._load(load_start)
  File "D:\Lingu\Linguflex\lingu\core\modules.py", line 193, in _load
    self.import_file(module_file, module["folder"], module)
  File "D:\Lingu\Linguflex\lingu\core\modules.py", line 87, in import_file
    mod = importlib.import_module(py_file_path)
  File "C:\Users\walke\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Lingu\Linguflex\lingu\modules\music\logic.py", line 2, in <module>
    from .handlers.youtube_player import YoutubePlayer
  File "D:\Lingu\Linguflex\lingu\modules\music\handlers\youtube_player.py", line 11, in <module>
    import vlc
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\vlc.py", line 220, in <module>
    dll, plugin_path  = find_lib()
  File "D:\Lingu\Linguflex\test_env\lib\site-packages\vlc.py", line 180, in find_lib
    dll = ctypes.CDLL('.\\' + libname)
  File "C:\Users\walke\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Lingu\Linguflex\libvlc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by KoljaB** [comment]
Oh damn. That is the music module which needs VLC player installed. I really need to rework the docs, sry.

**Comment by JeffYuY** [comment]
Oh ok, I'm installing it rn 👍 
Also why does the 。symbol exist in the settings.yaml, does it normally not cause problems?

**Comment by KoljaB** [comment]
Thanks dor pointing out the prob with the chinese sentence end punctuation. Will remove that char, I had no clue it causes issues on some systems.

**Comment by KoljaB** [comment]
Just looked it up, I think the whole sentence_delimiters parameter is not needed anymore and can be removed completely.

**Comment by KoljaB** [comment]
The sentence_delimiters parameter is part of the [stream2sentence](https://github.com/KoljaB/stream2sentence/blob/master/stream2sentence/stream2sentence.py#L214) library. Its purpose is to split tokens from the LLM into sentences for faster text-to-speech processing. I’m not sure why I originally included it in the listen section, it doesn’t really belong there. If anything, it would make more sense in the speech section, but even there, it’s not forwarded to stream2sentence. My best guess is that I put it in the wrong section with the intention to integrate it later and just forgot. Gotta love how ADHD keeps things... interesting.

**Comment by JeffYuY** [comment]
Ohh ok. I see

**Comment by JeffYuY** [comment]
I think this is resolved now, so I'll go ahead and close this.

**Comment by KoljaB** [comment]
No prob, let's solve it. I know, Linguflex is hard to install.

**Comment by KoljaB** [comment]
Ah just saw the new issue.
